#*******************************************************************************
# Description: This file contains the service definition for the application.
#*******************************************************************************
apiVersion: v1
kind: Service
metadata:
  name: demo-devsu-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-devsu-app